FROM drogonframework/drogon AS build

WORKDIR /src
COPY . .

RUN apt-get update && apt-get install -y libgtest-dev && rm -rf /var/lib/apt/lists/*

RUN rm -rf build && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j4 && \
    ctest --output-on-failure